spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=${PORT}

AI_BASE_URL=${AI_BASE_URL}
APP_BASE_URL=${APP_BASE_URL}